apiVersion: apps/v1
kind: Deployment
metadata:
  name: combined-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: combined-app
  template:
    metadata:
      labels:
        app: combined-app
    spec:
      containers:
        - name: spring-app
          image: your-registry/your-spring-app:latest
          ports:
            - containerPort: 8080
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
