spring:
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:habrpguser}
    password: ${DB_PASSWORD:pgpwd4habr}
    generate-ddl: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: proselyte

logging:
  level:
    org.springframework.data.r2dbc: DEBUG