version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: habrpguser
      POSTGRES_PASSWORD: pgpwd4habr
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
volumes:
  postgres_data: