spring:
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    generate-ddl: true

logging:
  level:
    org.springframework.data.r2dbc: DEBUG

url: http://localhost:8080//api/v1/companies
